### ISSUE TITLE
Cannot map fields from sample file

### ISSUE THREAD

**Issue by constantinospxm** [pluginsGLPI/datainjection#103]
Hi,
I have a sample file to inject into the plugin and link its fields to the corresponding table but it seems I can't find the correct field in the options. For example:
If I want to import computers, I create a model named computers and inject the sample file. I get the fields show up correctly but I can't link for example the field "Name" to the corresponding computers table field "Name" because there isn't one. Screenshot Available

![glpi](https://user-images.githubusercontent.com/41296979/42763606-39508a34-891c-11e8-935f-78f3b2297d01.png)
Can anyone help me please?
Am I doing something wrong?

Another Example:
There is no Serial Number field to add correspond with the serial number of the table I am importing. So I can't import laptops.

**Comment by mklimasz5** [comment]
Hi,
After upgrading to 9.3 with FI 2.6.1 (from 9.1.1 and FI 2.4.1) I've observed exactly the same behavior - vital fields are missing and none of the previously created templates works. I've also completed fresh test install of GLPI 9.3 + FI 2.6.1, but I can only confirm there is no change - fields like "Computers" -> "Name" are still missing.

**Comment by constantinospxm** [comment]
Downgraded to GLPI 9.2.4 and plugin is working fine. I guess for now if you want to use the plugin just stick with a previous version of GLPI

**Comment by amits170** [comment]
Hi, In model management mappings "Login" field is missing. Unable to import Users. Please help....

amit

**Comment by mklimasz5** [comment]
Hi
Problem is - our GLPI is full of data, so downgrade is not a viable option... At this moment I can only wonder how can we influence plugin's development Team to find out what might gone wrong (database scheme?) and ask for a fix.

**Comment by constantinospxm** [comment]
Thats what github does :)
They should watch those opened issues

**Comment by grigribou** [comment]
I have dame issue. 
I can’t inject various fields as computer name.
Computer - Name is not present en list!

**Comment by OscarBeiro** [comment]
Even after patching with @loicbenoit commit, and altering tables to InnoDB, error seems to persist.

**Comment by cedric-anne** [comment]
Hi all,

Can you try the fix https://github.com/pluginsGLPI/datainjection/pull/114 ?

Regards

**Comment by Gambity** [comment]
After @loicbenoit and @orthagh commits it starts working. Im able to import fields Name, SerialNumber.

**Comment by loicbenoit** [comment]
After installing fix for #114, found a minor unsolved issue with location_id when trying to import a Computer from CSV file.

### Expected
Computer field "location_id" recognized as "Lieu" (aka location).

### Current result
- Computer field "location_id" is not recognized.
- Correct field "Lieu" (aka location) is not available to select, at least in French.
- Automatic selection is "longitude" (incorrect)

![datainjection_bug103_not fully-solved_2018-08-21_14-58-47](https://user-images.githubusercontent.com/6154667/44423733-d853b300-a554-11e8-9c39-f10aa314c3a6.png)

**Comment by loicbenoit** [comment]
Can someone explain where to find the definition for blacklist codes in method plugins/datainjection/inc/commoninjectionlib.class.php::getBlacklistedOptions?

### What I know
It is related to search options and methods such as rawSearchOptionsToAdd(), but how do you know what code to use?

For example, in method "glpi/inc/location.class.php::rawSearchOptionsToAdd", how would you know that  you must use code "3" for "glpi_locations.completename" and code "101" for "glpi_locations.address"?

I'm trying to check if field "computer.location_id" is blacklisted or not?

**Comment by drummeroo** [comment]
Hello Guys,

I still have the same problem like @loicbenoit - issue with map location field in Computers.

Maybe Can You fix this bug and send new commit of new version ?

Very please - it's very important for us.

Thanks,

Regards.

**Comment by cedric-anne** [comment]
Hi,

I just investigate and this issue is due to the way the mapping is built. Fields proposal are based on `linkfield` of item "search options".

This `linkfield` is used by GLPI to handle table joins when searching/reading items data, and is automatically set if not defined in "search options" definition (see https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/search.class.php#L5860). Unless on specific cases, this `linkfield` will be the ID field of corresponding table.
On a computer, all fields related to `location` have same `linkfield`: `address`, `postcode`, `latitude`, `longitude`, `completename`, `town`, `state`, `country`.

Mapping field dropdown is built using this `linkfield` as an array key. As key value is unique, and as fields are assigned in a `foreach` loop , only last field is available (see: https://github.com/pluginsGLPI/datainjection/blob/develop/inc/injectiontype.class.php#L212). For `location` , `longitude` is the last assigned as it is the last declared in "search options" (see: https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/location.class.php#L121).

Two solutions can fix this problem:
1. Use id of search option instead of `linkfield` as key in mapping.
2. Use `table.field` instead of `linkfield` as key in mapping.

In both case, it requires a lot of work to modify all the mapping management and the way it is used when injecting files.

Regards

**Comment by loicbenoit** [comment]
Here's a suggested workaround for importing the location field, indirectly. Adapt as needed.

1. Group your imports by location (optional, but easier to manage).
2. In your CSV file, include a field to identify your imports. This will be your "import id".
2.1. For example, "import id" = "name yyyy-mm-dd-hh-ii"
2.2. You may add a field using plugin "Fields" or use an existing field. You may have to update your DataInjection importation model to use this workaround.
3. Import.
4. Search your imported records using your "import id" field.
5. Select all matches. Search results should match the content of your CSV file.
6. Use "Actions" > "Modify" to massively set the correct location for all selected items.

**Comment by cedric-anne** [comment]
Hi,

For location issue, please use #121 thread.

Regards
