### ISSUE TITLE
Data injection csv Location

### ISSUE THREAD

**Issue by mingosss** [pluginsGLPI/datainjection#121]
Hi
I can not map the location of the equipment, in the fields the location field does not appear
Thanks

**Comment by ExploitationSMAG** [comment]
Hello same problem here ! I can't specify a location when I'm trying to import computers ...

**Comment by cedric-anne** [comment]
Comment initialy done on #103.

Hi,

I just investigate and this issue is due to the way the mapping is built. Fields proposal are based on `linkfield` of item "search options".

This `linkfield` is used by GLPI to handle table joins when searching/reading items data, and is automatically set if not defined in "search options" definition (see https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/search.class.php#L5860). Unless on specific cases, this `linkfield` will be the ID field of corresponding table.
On a computer, all fields related to `location` have same `linkfield`: `address`, `postcode`, `latitude`, `longitude`, `completename`, `town`, `state`, `country`.

Mapping field dropdown is built using this `linkfield` as an array key. As key value is unique, and as fields are assigned in a `foreach` loop , only last field is available (see: https://github.com/pluginsGLPI/datainjection/blob/develop/inc/injectiontype.class.php#L212). For `location` , `longitude` is the last assigned as it is the last declared in "search options" (see: https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/location.class.php#L121).

Two solutions can fix this problem:
1. Use id of search option instead of `linkfield` as key in mapping.
2. Use `table.field` instead of `linkfield` as key in mapping.

In both case, it requires a lot of work to modify all the mapping management and the way it is used when injecting files.

Regards

**Comment by loicbenoit** [comment]
### Proposal for workaround
In GLPI location class, move "completename" to end of array. I will open a ticket in GLPI project to discuss this.

### Not a bug fix, but seems to work
It doesn't fix the bug, but makes it work with no observed side effect so far. The solutions proposed by Cedric-Anne seems to be the proper way to fix the issue permanently, but it will take more time.

**Comment by mingosss** [comment]
Thanks a lot this work for me

**Comment by cedric-anne** [comment]
Hi,

I proposed a more reliable solution that would fix this problem globally without having to touch core of GLPI. See https://github.com/pluginsGLPI/datainjection/pull/122.

@loicbenoit, as you take some time to investigate the problem, ould you tell me what you think of this solution ?

Regards

**Comment by cedric-anne** [comment]
#122 validated by @loicbenoit .

**Comment by abhishek-rajput-44** [comment]
Hi, I have installed glpi v10.00 on my local machine using XAMPP. Also installed latest plugin generic object management (version 2.12.1) to create new assets object and data / file injection (version 2.11.2) to import data by csv file for created new object. For example i have created new asset object called "Television" and i am using csv file with two columns "Name", "Location" to import data for the same. data is inserted but location field is not reflected in the list view.
