### ISSUE TITLE
What is csv template for import computers ?

### ISSUE THREAD

**Issue by dssoft32** [pluginsGLPI/datainjection#148]
What is the template for import computers in CSV format ? or way from software to get template.

**Comment by ccastelb** [comment]
@dssoft32 
@dssoft32 
The template for importing the various components (computers, printers, phones) you build yourself, you should simply consider which fields you want to be imported into glpi and leave them as headers in a csv file. for example
hostname
serial
other serial
manufacturer
model
etc.
it is important to consider that the file be separated by "," or ";"
and this must be configured at the time of the creation of the template so that the mapping of fields is done in the correct way

**Comment by ccastelb** [comment]
@dssoft32 
The template for importing the various components (computers, printers, phones) you build yourself, you should simply consider which fields you want to be imported into glpi and leave them as headers in a csv file. for example
hostname
serial
other serial
manufacturer
model
etc.
it is important to consider that the file be separated by "," or ";"
and this must be configured at the time of the creation of the template so that the mapping of fields is done in the correct way
