### ISSUE TITLE
log.class.php at line 727 and line 728

### ISSUE THREAD

**Issue by ukkt** [pluginsGLPI/datainjection#211]
Hello,

I have a little problem with GLPI and now I have noticed that the issue only exist for devices witch were created be the data injection. Underneath I have copied the Github GLPI issue:

https://github.com/glpi-project/glpi/issues/7821

Describe the bug

I get a php-notice when I go to Historical on every typ of device.
PHP Notice (8): Undefined index: table in C:\xampp\htdocs\glpi\inc\log.class.php at line 727
PHP Notice (8): Undefined index: table in C:\xampp\htdocs\glpi\inc\log.class.php at line 728

Page(s) URL

.../glpi/front/monitor.form.php?id=87

To reproduce

Go to one Device
Click on 'Historical '

![](https://user-images.githubusercontent.com/49140655/89163696-45ac5300-d576-11ea-8846-0dea89ddc973.JPG)

**Comment by ukkt** [comment]
no help?

**Comment by Mirkk** [comment]
Same issue here, for all computers that were changed with Datainjection. It shows the correct number of history entries, and pagination of them (e.g. 20 per page), but they are not displayed in the list.

GLPI 9.5.1, plugin 2.8.0 - however in the changelogs of 2.8.1 I couldn't find anything about relevant bug fixes.

Thank you for feedback

**Comment by cconard96** [comment]
I haven't noticed any missing entries but have seen that error today after upgrading our instance.
Does it go away for you too if you make the following change?
Line 722 in `inc/log.class.php` change `if ($key2 == $data["id_search_option"]) {` to `if ($key2 === $data["id_search_option"]) {`.

**Comment by Mirkk** [comment]
Thank you very much @cconard96 this resolved the error, and all entries are displayed again! 
However, if you just upgraded, it means that the error is still present in GLPI 952 and datainjection 2.8.1...
Were you able to understand if it the error is on the datainjection side (and this is just a workaround) or in the core?

The bug is present only on the Computer asset, and only if there is no filter. Setting a first filter while using the workaround above, then it works until you remove all filters.

**Comment by Mirkk** [comment]
Update: it happens if in table glpi_logs "id_search_options" = 0 and linked_action = 0. Putting e.g. id_search_option to 1 resolves the error.
All entries with "id_search_options" = 0 and linked_action = 0 were written by the datainjection plugin. It seems that older GLPI versions did not have any problem with this data (some 0/0 entries are years old, as you see in the example below).


Example:
| id      | itemtype | items_id | itemtype_link | linked_action | user_name                | date_mod            | id_search_option | old_value           | new_value            |
| 1846051 | Computer |      620 |               |             0 | phoenix (23)             | 2017-07-27 11:53:20 |                0 |                     |                      |

**Comment by cconard96** [comment]
I'm not sure yet which side is the cause of the issue, but this gives me a place to start investigating. I think the issue is just caused in the core, but maybe the core never has `id_search_options` set to 0, so it is only noticeable with this plugin. Without strict comparison `===` "common" equals 0 which is really odd and probably not intended since common isn't a search option, its a group.

**Comment by Mirkk** [comment]
Note: on GLPI 9.4.6 it works, with the same data and "0", despite inc/log.class.php has no relevant changes.
Thanks for investigating.
