### ISSUE TITLE
Fields locked after upload

### ISSUE THREAD

**Issue by Lunik971** [pluginsGLPI/datainjection#238]
Hello,

I just start with GLPI and all plugin. I am using data injection to load our computer delivery. no issue at the moment.
But after when the computer is installed and connected to the the network we use OCS to made an automatic inventory.
Here is my issue, OCS can not update the name the data for the existing serial numer and i think it is because 
some fields are blocked after the data injection upload.
Someone know how to manage locked fields with data injection ?

Thank you by advance for your help.

GLPI 9.5.5 
Datainjection 2.9.0
ocsinventoryng 1.7.3

**Comment by Mirkk** [comment]
Interested on this, too. Is nobody here that has an Idea on how to handle locks with datainjection? For me the best and clearest behaviour would be that datainjection does never care about locks and never locks (or at least that this could be set).
This because datainjection is done by a user (usually) knowing what he does. E.g. there is the need to mass update some fields to correct data because of some issues e.g. with OCS.
Thanks for any feedback!

**Comment by Mirkk** [comment]
Hi @stonebuzz ! Why do you close such issues as completed? They don't seem to be completed at all... I fully understand that they are of importance of nearly 0 for the actual project (and will maybe no more be resolved by Teclib), but if someone hits these, it is really useful to understand that this is known also to others and an open issue. "Completed" reads like "issue resolved" - this is not the case.
