### ISSUE TITLE
Impossible to import ip adress

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/datainjection#26]
Hello

When I import ip adress nothing is imported

glpi 9.2 same on glpi 9.1.1

**Comment by gaionim** [comment]
Same here.
Try to import printers.

`** PHP Notice(8): Undefined index: id
  Backtrace :
  ...injection/inc/networknameinjection.class.php:97 
  ...injection/inc/commoninjectionlib.class.php:1329 PluginDatainjectionNetworkNameInjection->addSpecificNeededFields()
  ...injection/inc/commoninjectionlib.class.php:1470 PluginDatainjectionCommonInjectionLib->addNeededFields()
  ...datainjection/inc/printerinjection.class.php:92 PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
  plugins/datainjection/inc/engine.class.php:147     PluginDatainjectionPrinterInjection->addOrUpdateObject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()
`

The problem seems in

`function addSpecificNeededFields($primary_type,$values) {

           echo '<mauro>';

             echo ''. json_encode( $values ) .'';

             echo '</mauro>';

      $fields['items_id']  = $values['NetworkPort']['id'];     < ------------------------------

      $fields['itemtype']      = "NetworkPort";

      return $fields;

   }

`

Values are 
`{"Printer":{"name":"VAL-ST-1343","manufacturers_id":"169","printermodels_id":"1","serial":"S74636C6600PYG","entities_id":"0","date_creation":"2018-02-02 09:25:46","id":"1047","is_recursive":"0","date_mod":"2018-02-02 10:03:48","contact":null,"contact_num":null,"users_id_tech":"0","groups_id_tech":"0","otherserial":null,"have_serial":"0","have_parallel":"0","have_usb":"0","have_wifi":"0","have_ethernet":"1","comment":null,"memory_size":null,"locations_id":"0","domains_id":"0","networks_id":"0","printertypes_id":"0","is_global":0,"is_deleted":"0","is_template":"0","template_name":"0","init_pages_counter":"0","last_pages_counter":"0","users_id":"0","groups_id":"0","states_id":"0","ticket_tco":"0.0000","is_dynamic":"0"},
"NetworkName":{"ipaddresses_id":"10.10.9.66","itemtype":"Printer","items_id":"1047","entities_id":"0"},
"NetworkPort":{"mac":"00:21:b7:6d:51:b8"}
}`

I guess NetworkPort must be created before to have 'ip' to pass.
