### ISSUE TITLE
Table glpi_plugin_datainjection_models : migration V10

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/datainjection#355]
Bonjour
Lors de la migration en V10, l'etape de vérification des zones signées signale que la zone entities_id ne peut etre convertie car elle contient des valeurs negatives. (table glpi_plugin_datainjection_models)

Certes dans les migrations dans le plugin, les valeurs sont mises à 0, mais il faudrait 'modifier' la table afin que la valeur par defaut soit mise à 0 et non -1.

![image](https://github.com/pluginsGLPI/datainjection/assets/42341169/9f27fa42-99c7-4dba-b0b4-c699e6c3fd50)

Merci

**Comment by stonebuzz** [comment]
Hi @EC2311 

The default value for the entity has been corrected since version 2.0 of the plugin.

You may have encountered problems with this update.

I advise you to update the default value manually (via an SQL query).

The message indicates that there are rows in this table with the value -1 (for entities_id column)

The rows need to be adjusted manually (via an SQL query) to set the value to 0 instead.

Best regzards
