### ISSUE TITLE
Error: SQL Warnings: 1292

### ISSUE THREAD

**Issue by camiloperez861** [pluginsGLPI/datainjection#371]
Muy buenos días

Solicito su apoyo con el siguiente error: 

Al monento de crear un modelo aparece este error:

SQL Warnings: 1292: Truncated incorrect DECIMAL value: '' in query "(SELECT `itemtype` FROM `glpi_plugin_datainjection_models` WHERE `id` = '') UNION (SELECT DISTINCT `itemtype` FROM `glpi_plugin_datainjection_mappings` WHERE `models_id` = '') UNION (SELECT DISTINCT `itemtype` FROM `glpi_plugin_datainjection_infos` WHERE `models_id` = '')"

![err](https://github.com/pluginsGLPI/datainjection/assets/89992358/61949c4a-efec-4ccf-8c22-5bac5787602a)

**Comment by stonebuzz** [comment]
Hi

Can you show us the data you insert in the form when you create the model?

Best regards

**Comment by aurelien-unilim** [comment]
Hello
to be more precise, the problem occurs when you try to add a model by clicking on "+Add". Then you get this error message. I've attached a screenshot to show you exactly what happens.

https://postimg.cc/8jmzGpxD/0653ac60

Best regards,

**Comment by PlaneNuts** [comment]
@stonebuzz - Hi, while I was trying to dig into the issue I submitted a few days ago I came across this too. 

I dug into this a bit and I see that `*/front/model.form.php` sets `$_GET["id"]` to `" "` if it's not set like the GLPI item addition forms. 

![image](https://github.com/user-attachments/assets/561dd90e-4a7c-4a02-bad8-daa56c3fecf2)

But, one thing I noticed is that the GLPI addition forms first call `front/setup.templates.php` 

I clicked "Add Computer" to see how things differed from the plugin form and stepping through line 60 in this file eventually brought me to line 5305 in `src/CommonDBTM.php` where this link is getting set with and id of `-1` so when the request is finally being made to the DB, it's not sending an empty string. 

![image](https://github.com/user-attachments/assets/aca69157-b2ef-48be-8651-038127497fd2)


![image](https://github.com/user-attachments/assets/54d40d6a-3bb3-4742-8455-47df04c905b2)

I tried setting `0` instead of `" "` in `model.form.php` and this seemed to clear the error, but I'm not sure if this break anything anywhere else (I was able to add a new model with this), so I'm a bit hesitant to submit a PR, but hopefully this gives some insight into what's going on

![image](https://github.com/user-attachments/assets/f020074c-3f30-4a7c-8e3a-640066c26187)

**Comment by PlaneNuts** [comment]
Deleted my last comment as I was way off on the actual cause, but I think I actually found it.

Looks like this is being through because of the query in the `checkRightOnModel()` function in `/inc/model.class.php`

It's trying to run this even if `$models_id` is blank

![image](https://github.com/user-attachments/assets/cd4295b3-b058-4e01-9b24-d46f99ef4b2c)

Setting `$modes_id` to -1 if it's null cleared the error

![image](https://github.com/user-attachments/assets/7cb9ff35-73b6-48fa-98ad-99d9e3e452ab)
